restaurant/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :dishes
  
  resources :orders do
    member do 
      get 'prepare'
      post 'add'
      delete 'remove'
      put 'submit'
    end
  end
  
  get '/restaurant/orders' => 'restaurant_orders#index'
  put '/restaurant/orders/:id/prepare' => 'restaurant_orders#prepare', as: :prepare
  put '/restaurant/orders/:id/enroute' => 'restaurant_orders#enroute', as: :enroute
  put '/restaurant/orders/:id/deliver' => 'restaurant_orders#deliver', as: :deliver
  put '/restaurant/orders/:id/complete' => 'restaurant_orders#complete', as: :complete

  root 'orders#index'
  
end

restaurant/app/models/dish.rb
class Dish < ApplicationRecord
   
    has_many :order_dishes
   
    has_many :orders, through: :order_dishes

end

restaurant/app/models/order.rb
class Order < ApplicationRecord
  
  belongs_to :user
  
  has_many :order_dishes
  
  has_many :dishes, through: :order_dishes
  
  def total
    total = 0
    dishes.each do |dish|
      total = total + dish.price
  end
    return total
end

end

restaurant/app/models/order_dish.rb
class OrderDish < ApplicationRecord
    
  belongs_to :order
  
  belongs_to :dish
  
end

restaurant/app/models/user.rb
class User < ApplicationRecord

  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

restaurant/app/controllers/dishes_controller.rb
class DishesController < ApplicationController

    def index
        @dishes = Dish.all
    end
    
    def new
        @dish = Dish.new
    end
    
    def create
        dish = Dish.new
        dish.name = params[:dish][:name]
        dish.description = params[:dish][:description]
        dish.picture = params[:dish][:picture]
        dish.price = params[:dish][:price]
        dish.save
        redirect_to dishes_path
    end
    
    def edit
        @dish = Dish.find(params[:id])
    end
    
    def update
        dish = Dish.find(params[:id])
        dish.name = params[:dish][:name]
        dish.description = params[:dish][:description]
        dish.picture = params[:dish][:picture]
        dish.price = params[:dish][:price]
        dish.save
        redirect_to dishes_path
    end
    
    def delete
        dish = Dish.find(params[:id])
    end
end


    

restaurant/app/controllers/orders_controller.rb
class OrdersController < ApplicationController
    
    before_action :authenticate_user!
    
    def index
        @orders = Order.where(user_id: current_user.id)
    end
    
    def show
    end
    
    def new
        @order = Order.new
    end
    
    def create
        @order = Order.new
        @order.street_address = params[:order][:street_address]
        @order.city = params[:order][:city]
        @order.state = params[:order][:state]
        @order.zip = params[:order][:zip]
        @order.status = 'created'
        @order.user_id = current_user.id
        @order.save
        redirect_to prepare_order_path(@order)
    end
    

    
    def prepare
        @order = Order.find(params[:id])
        @dishes = Dish.all
        @total = 0
        @order.dishes.each do |dish|
            @total = @total + dish.price
        end
    end
    
    def add
        @order = Order.find(params[:id])
        order_dish = OrderDish.new
        order_dish.dish_id = params[:dish_id]
        order_dish.order_id = params[:id]
        order_dish.save
        redirect_to prepare_order_path(@order)
    end
    
    def remove
        @order = Order.find(params[:id])
        order_dish = OrderDish.find(params[:order_dish_id])
        order_dish.destroy
        redirect_to prepare_order_path(@order)
    end
    
    def submit
        @order = Order.find(params[:id])
        @order.status = 'submitted'
        @order.save
        redirect_to orders_path
    end

    

end

restaurant/app/controllers/restaurant_orders_controller.rb
class RestaurantOrdersController < ApplicationController
    def index
        #orders that are submitted, preparing, enroute
        @orders = Order.where(status: ['submitted', 'preparing', 'enroute', 'delivering', 'complete'])
    end
    
    def prepare
        @order = Order.find(params[:id])
        @order.status = "preparing"
        @order.save
        redirect_to restaurant_orders_path
    end
    
    def enroute
        @order = Order.find(params[:id])
        @order.status = "enroute"
        @order.save
        redirect_to restaurant_orders_path
    end
    
    def deliver
        @order = Order.find(params[:id])
        @order.status = "delivering"
        @order.save
        redirect_to restaurant_orders_path
    end
    
    def complete
        @order = Order.find(params[:id])
        @order.status = "complete"
        @order.save
        redirect_to restaurant_orders_path
    end
end

restaurant/app/helpers/dishes_helper.rb
module DishesHelper
end

restaurant/app/helpers/orders_helper.rb
module OrdersHelper
end

restaurant/app/helpers/restaurant_orders_helper.rb
module RestaurantOrdersHelper
end

restaurant/app/views/dishes/edit.html.erb
<div>
<%= form_for @dish do |f| %>
    <div>
        <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
        <%= f.text_area :description, placeholder: 'Description' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.number_field :price, placeholder: 'Price'%>
    </div>
    <div>
        <%= f.submit 'Save' %>
    </div>
<% end %>
</div>

restaurant/app/views/dishes/index.html.erb
<div>
<%= link_to 'New', new_dish_path %>
    
<% @dishes.each do |dish| %>
    <div>
        <%= dish.name %>
    </div>
    <div>
        <p><%= dish.description %></p>
    </div>
    <div>
        <%= image_tag dish.picture, height: 100 %>
    </div>
    <div>
        <p>$<%= dish.price %></p>
    </div>
    <div>
        <%= link_to 'Edit', edit_dish_path(dish) %>
    </div>
<% end %>
</div>

restaurant/app/views/dishes/new.html.erb
<div>
<%= form_for @dish do |f| %>
    <div>
        <%= f.text_field :name, placeholder: 'Name' %>
    </div>
    <div>
        <%= f.text_area :description, placeholder: 'Description' %>
    </div>
    <div>
        <%= f.text_field :picture, placeholder: 'Picture' %>
    </div>
    <div>
        <%= f.number_field :price, placeholder: 'Price'%>
    </div>
    <div>
        <%= f.submit 'Save' %>
    </div>
<% end %>
</div>

restaurant/app/views/restaurant_orders/index.html.erb
<% @orders.each do |order| %>
    <div class="row">
        <div class="col-2">
            <%= order.status %>
        </div>
        <div class="col-6">
            <%= order.street_address %>
            <%= order.city %>
            <%= order.state %>
            <%= order.zip %>
        </div>
        <div class="col-2">
            $<%= order.total %>
        </div>
        
<div class="col-2">
    <% if order.status == 'submitted' %>
        <%= link_to 'Prepare', prepare_path(order), method: :put, class: 'btn btn-sm btn-secondary' %>
    <% elsif order.status == 'preparing' %>
        <%= link_to 'Enroute', enroute_path(order), method: :put, class: 'btn btn-sm btn-secondary' %>
    <% elsif order.status == 'enroute' %>
        <%= link_to 'Deliver', deliver_path(order), method: :put, class: 'btn btn-sm btn-secondary' %>
    <% elsif order.status == 'delivering' %>
        <%= link_to 'Complete', complete_path(order), method: :put, class: 'btn btn-sm btn-secondary' %>
    <% end %>
</div>

<% if order.status == 'preparing'%>
        <% order.order_dishes.each do |order_dish| %>
            <div class='media mt-3'>
                <%= image_tag order_dish.dish.picture, height: 75, width: 75, class: "mr-3" %>
                <div class="media-body">
                    <h6>
                        <%= order_dish.dish.name %>
                    </h6>
                </div>
            </div>
        <% end %>
    <% end %>
<% end %>
        
   