questions_box/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 
  get '/user_questions/view' => 'user_questions#view'

 
  resources :questions 
  
  resources :user_questions do
    member do
      get :add
      post :add
      delete :remove
    end
  end
  
  resources :types
  
  root 'questions#index'
  
  get '/questions/search' => 'questions#search'
  
  get '/questions/results' => 'questions#results'
  
  post '/questions/results' => 'questions#results'

  
  get '/user_questions/search' => 'user_questions#search'
  
  get '/user_questions/results' => 'user_questions#results'
  
  post '/user_questions/results' => 'user_questions#results'

end

questions_box/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

questions_box/app/models/question.rb
class Question < ApplicationRecord
    has_many :user_questions
    has_many :users, through: :user_questions
    belongs_to :type
end

questions_box/app/models/type.rb
class Type < ApplicationRecord
    has_many :questions
end

questions_box/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
 
  has_many :user_questions
  has_many :questions, through: :user_questions
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

questions_box/app/models/user_question.rb
class UserQuestion < ApplicationRecord
    belongs_to :question
    belongs_to :user
end

questions_box/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

questions_box/app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
    
    skip_before_action :verify_authenticity_token

    def index
        @questions = Question.all
        @type = Type.all
        # query = "%#{params[:type_id]}%"
        # @type = Type.where("id LIKE ?", query)
        
        # @questions = Question.where(user_id: current_user.id)
    end
    
    def new
        @question = Question.new
        @type = Type.all
    end
    
    def create
        @type = Type.all
        @question = Question.new
        @question.q_title = params[:question][:q_title]
        @question.answer = params[:question][:answer]
        @question.type_id   = params[:type_id]
        @question.resource_name = params[:question][:resource_name]
        @question.web_link = params[:question][:web_link]
        @question.save
        redirect_to questions_path
    end
    
    def edit
        @type = Type.all
        @question = Question.find(params[:id])
    end
    
    def update
        @type = Type.all
        question = Question.find(params[:id])
        question.q_title = params[:question][:q_title]
        question.answer = params[:question][:answer]
        question.type_id   = params[:type_id]
        question.resource_name = params[:question][:resource_name]
        question.web_link = params[:question][:web_link]
        question.save
        redirect_to questions_path
    end
    
    def destroy
        @question = Question.find(params[:id])
        @question.destroy
        redirect_to questions_path 
    end
    
    def search
        @questions = Question.all
        @type = Type.all
    end
       
    def results
        query = "%#{params[:query]}%"
        @questions = Question.where("q_title LIKE ?", query) 
        @type = Type.all
    end
end

questions_box/app/controllers/types_controller.rb
class TypesController < ApplicationController

    def index
        @types = Type.all
    end
    
    def new
        @type = Type.new
    end
    
    def create
        type = Type.new
        type.title = params[:type][:title]
        type.description = params[:type][:description]
        type.tips = params[:type][:tips]
        type.save
        redirect_to types_path
    end
    
    def edit
        @type = Type.find(params[:id])
    end
    
    def update
        type = Type.find(params[:id])
        type.title = params[:type][:title]
        type.description = params[:type][:description]
        type.tips = params[:type][:tips]
        type.save
        redirect_to types_path
    end
    
    def show
        @type = Type.find(params[:id])
        @questions = Question.all
    end
    
    def destroy
        @type = Type.find_by(id: params[:id])
        @type.destroy
        redirect_to types_path
    end
    
end

questions_box/app/controllers/user_questions_controller.rb
class UserQuestionsController < ApplicationController
    
    skip_before_action :verify_authenticity_token
    
    before_action :authenticate_user!
    
    def index   
    end    
    
    def search
        @questions = Question.all
        @type = Type.all
    end
       
    def results
        query = "%#{params[:query]}%"
        @questions = Question.where("q_title LIKE ?", query) 
        @type = Type.all
    end
    
    def add
        @questions = Question.find(params[:id])
        @user_question = UserQuestion.new
        @user_question.question_id = params[:id]
        @user_question.user_id = current_user.id
        @user_question.save
        redirect_to user_questions_view_path(@questions)
        
        # @questions = Question.find(params[:id])
        # user_question = UserQuestion.new
        # user_question.question_id = params[:question_id]
        # user_question.user_id = current_user.id
        # user_question.save
        # redirect_to user_questions_view_path(@questions)
        
        #   @question.q_title = params[:question][:q_title]
        # @question.answer = params[:question][:answer]
        # @question.type_id   = params[:type_id]
        # @question.resource_name = params[:question][:resource_name]
        # @question.web_link = params[:question][:web_link]
    end

    def view
        @user_question = UserQuestion.all
        @questions = Question.all
        @type = Type.all
    end
    
        #     @restaurant = Restaurant.find(params[:id])
        # @diet = Diet.all
    
    
    #     def add_diet
    #     restaurant = Restaurant.find(params[:restaurant_id])
    #     restaurant_diet = RestaurantDiet.new
    #     restaurant_diet.restaurant_id = params[:restaurant_id]
    #     restaurant_diet.diet_id = params[:diet_id]
    #     restaurant_diet.save
    #     redirect_to restaurant_path(restaurant.id)
    # end
    
    # def destroy
    #     @restaurants = Restaurant.find(params[:id])
    #     @restaurant.destroy
    #     redirect_to '/restaurants'
      
    def remove
         
        @user_question = UserQuestion.find(params[:id])
        @user_question.destroy
        redirect_to user_questions_view_path(@questions)
 
    #  @question = Question.find(params[:id])
    #     @question.destroy
    #     redirect_to questions_path 
 
    # def destroy
    #     # @user_question = UserQuestion.all


    #     # @questions = Question.find(params[:id])
    #     # @user_question = UserQuestion.find(params[:id])
    #     # user_question.question_id = params[:id]
    #     @user_question = UserQuestion.find(params[:id])
    #     @user_question.destroy
    #     redirect_to user_questions_view_path(@questions)
    end
end

questions_box/app/helpers/application_helper.rb
module ApplicationHelper
end

questions_box/app/helpers/questions_helper.rb
module QuestionsHelper
end

questions_box/app/helpers/types_helper.rb
module TypesHelper
end

questions_box/app/helpers/user_questions_helper.rb
module UserQuestionsHelper
end

questions_box/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <title>QuestionsBox</title>

    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <style>
      .a {
        border-style: solid;
        border-color: black;
        border-width: 2px;
      }
      
      .title {
        color: #20B2AA;
        margin-top: 30px;
        font-family: verdana;
      }
      
      .subtitle {
        color: #E94A22;
        margin-top: 10px;
      }
      
      .body {
        margin: 10px;
      }
      
      .menu {
        font-family: verdana;
        color: black;
        margin-right: 15px;
        margin-left: 15px;
        height: 45px;
      }
      .b {
        background: #FFF1C1;
      }
      .ques {
        font-family: verdana;
        font-weight: bold;
        color: #F2466E; 
        font-style: italic;
      }
      .ans {
        font-family: verdana;
        font-weight: bold;
        font-style: italic;
      }
      .box {
        padding: 10px;
      }
      .sub {
        color: #20B2AA;
        font-family: verdana;
        text-align: center;
        padding: 10px;
      }
      .type {
        font-family: verdana;
        font-style: italic;
      }
      .typetitle {
        font-family: verdana;
        text-align: center;
        padding: 10px;
      }
         
    </style>
  </head>

  <body class="body">
    <div class="a">
      <div class="row">
        <div class="col-md-1">
          <img src='https://dinnerplanner.com/wp-content/uploads/2017/05/box-of-questions.jpg' height=160px>
        </div>
        <div class="col-md-11">
          <h1 class='title'><b>QUESTION BOX</b></h1>
          <h3 class='subtitle'><i>An app for reproductive health educators in answering our youth's most blush worthy questions!</i></h3>
        </div>
      </div>
    </div> 
    <div>
    <%= yield %>
    </div>
  </body>
</html>

questions_box/app/views/types/edit.html.erb
<div class="sub">
    <h3><b>Administrator's Page: Edit Question Type</b></h3>
</div>

<div>
    <%= form_for @type do |f| %>
        <div class="form-group">
        <label>Enter Question Type</label>
            <div>
                <%= f.text_field :title, placeholder: 'Question Type' %>
            </div>
        </div>
        <div class="form-group">
        <label>Enter Description</label>
            <div>
                <%= f.text_area :description, placeholder: 'Description', cols: 165, rows: 3 %>            
            </div>
        </div>
        <div class="form-group">
        <label>Enter Facilitator Tips</label>
            <div>
                <%= f.text_area :tips, placeholder: 'Facilitator Tips', cols: 165, rows: 3  %>
            </div>
        </div>
        <div class="form-group">
                <%= f.submit 'Save' %>
        </div>
    <% end %>
</div>

questions_box/app/views/types/index.html.erb
<div class="b">
    <div class="menu">
        <div class="row">
            <div class="col-md-4">
                <h5><b>Navigation Menu:</b></h5>
            </div>
            <div class="col-md-4">
                <img src="https://junkmailimages.blob.core.windows.net/large/80c5d9d9d43b4626bf7173fc9724afde.jpg" height=35px>
                <%= link_to 'Return Home', types_path %>
            </div>
            <div class="col-md-4">
                <img src="https://cdn4.iconfinder.com/data/icons/simplicio/128x128/file_add.png" height=35px>
                <%= link_to 'Add New Question Type', new_type_path %>
            </div>
        </div>
    </div>
</div>
<br>
<div class="sub">
    <h3><b>Administrator's Page: Questions Type Index</b></h3>
</div>

<div>
    <% @types.each do |type| %>
<div class="box">
    <div class="row">
        <div class="col-md-2">
            <h4>Question Type:</h4>
        </div>
        <div class="col-md-10">
            <h4><%= type.title %></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <h5><i>Description:</i></h5>
        </div>
        <div class="col-md-10">
            <p><%= type.description %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <h5><i>Facilitator Tips:</i></h5>
        </div>
        <div class="col-md-10">
            <p><%= type.tips %></p>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <img src="https://cdn4.iconfinder.com/data/icons/web-ui-color/128/Edit-512.png" height=35px>
            <%= link_to 'Edit Question Type', edit_type_path(type) %>
            <img src="https://cdn2.iconfinder.com/data/icons/metro-uinvert-dock/256/Recycle_Bin_Full.png" height=35px>
            <%= link_to 'Delete Question Type', type_path(type), method: :delete %>
            <img src="http://www.clker.com/cliparts/w/1/x/B/F/C/question-mark-hi.png" height=35px>
            <%= link_to 'View Associated Questions', type_path(type), method: :get %>
        </div>
    </div>
</div>
    <% end %>
</div>

questions_box/app/views/types/new.html.erb
<div class="sub">
    <h3><b>Administrator's Page: Add New Question Type</b></h3>
</div>

<div>
<form>
    <%= form_for @type do |f| %>
        <div class="form-group">
        <label>Enter Question Type</label>
            <div>
                <%= f.text_field :title, placeholder: 'Question Type' %>
            </div>
        </div>
        <div class="form-group">
        <label>Enter Description</label>
            <div>
                <%= f.text_area :description, placeholder: 'Description', cols: 165, rows: 3 %>            
            </div>
        </div>
        <div class="form-group">
        <label>Enter Facilitator Tips</label>
            <div>
                <%= f.text_area :tips, placeholder: 'Facilitator Tips', cols: 165, rows: 3  %>
            </div>
        </div>
        <div class="form-group">
            <%= f.submit 'Save' %>
        </div>
    <% end %>
</form>
</div>
    

questions_box/app/views/types/show.html.erb
<div class="b">
    <div class="menu">
        <div class="row">
            <div class="col-md-4">
                <h5><b>Navigation Menu:</b></h5>
            </div>
            <div class="col-md-4">
                <img src="https://junkmailimages.blob.core.windows.net/large/80c5d9d9d43b4626bf7173fc9724afde.jpg" height=35px>
                <%= link_to 'Return Home', types_path %>
            </div>
            <div class="col-md-4">
                <img src="https://cdn4.iconfinder.com/data/icons/simplicio/128x128/file_add.png" height=35px>
                <%= link_to 'Add New Question Type', new_type_path %>
            </div>
        </div>
    </div>
</div>
<br>
<div class="sub">
    <h3><b>Administrator's Page: Viewing Associated Question For</b></h3>
    <h3><i><%= @type.title %></i></h3>
</div>
<div>
    <% @type.questions.each do |question| %>
<div class="box">
    <div class="row">
        <div class="col-md-2">
            <h4 class="ques">Question:</h4>
        </div>
        <div class="col-md-10">
            <h4><%= question.q_title %></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
            <h4 class="ans">Answer:</h4>
        </div>
        <div class="col-md-10">
            <h4><%= question.answer  %></h4>
        </div>
    </div>
    <div class="row">
        <div class="col-md-2">
        </div>
        <div class="col-md-10">
            <h4><i>For more information visit:</i> <a href="<%= question.web_link %>"><%= question.resource_name %></a></h4>
        </div>
    </div>
<div>
<% end %>
</div>